# fly.toml app configuration file generated for holy-cloud-7839 on 2023-09-05T20:53:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "holy-cloud-7839"
primary_region = "yyz"

[experimental]
  auto_rollback = true


[build]
  [build.args]
    NODE_VERSION = "16.20.2"

#[deploy]
#  release_command = "node index.js"


[processes]
  app = "node index.js"


[[services]]
internal_port = 3000
processes = ["app"]
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443


[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = 1000000
grace_period = "5s"
method = "get"
path = "/health"
protocol = "http"
timeout = 2000
tls_skip_verify = false

[[services.http_service]]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
